version: '2'
catalog:
  name: imagepuller
  version: 0.1.0
  description: A script to pull images for a specific Rancher version to speed up upgrades
  minimum_rancher_version: v1.6.0
  questions:
    - variable: CHECK_CPU_USAGE
      label: CHECK_CPU_USAGE
      description: Enable CPU usage check
      type: boolean
      default: true
    - variable: CPU_USAGE_MAX
      label: CPU_USAGE_MAX
      description: Maximum CPU usage in % to halt pulling images
      type: int
      default: 75
    - variable: CPU_SLEEP
      label: CPU_SLEEP
      description: Amount of seconds to sleep when cpu usage is too high 
      type: int
      default: 120
    - variable: PRIVILEGED
      label: PRIVILEGED
      description: Run as privileged (e.g. when SELinux is enabled)
      type: boolean
      default: false
    - variable: RANDOM_SLEEP
      label: RANDOM_SLEEP
      description: Sleep a "random" amount of seconds between image pulls
      type: boolean
      default: false
    - variable: RANCHER_VERSION
      label: RANCHER_VERSION
      description: Reference version to identify what images to pull
      type: string
      default: v1.6.14
services:
  imagepuller:
    start_on_create: true
