version: "2"

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    links:
      - metrics:metrics

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "${GF_SECURITY_ADMIN_PASSWORD}"
      GF_USERS_ALLOW_SIGN_UP: "${GF_USERS_ALLOW_SIGN_UP}"
 
  metrics:
    tty: true
    stdin_open: true
    image: infinityworks/github-exporter:latest 
    environment:
      REPOS: "${REPOS}"
      GITHUB_TOKEN: "${GITHUB_TOKEN}"
